### ISSUE TITLE
What's your trick for dealing with shitty GitHub issues?

### ISSUE THREAD

**Issue by passy** [arthurvr/ama#14]
Even though it's an Ask Me Anything, it's not an Answer Anything, so feel free to skip this one. :)

I personally get very easily frustrated seeing rude issues opened on my projects, but you have to deal with that stuff on an entirely different level. How do you stay motivated and keep doing so much amazing stuff and not just throw the towel?

**Comment by arthurvr** [comment]
Excellent question. When it's all done I'm going to do a serious write-up about this all, though here you have a kinda incomplete answer.

> I personally get very easily frustrated seeing rude issues opened on my projects

I do too. I definitely do.


> How do you stay motivated and keep doing so much amazing stuff and not just throw the towel?

When I made a nitpicky comment and somebody's mad, I feel bad about that, because it's my fault. It's important to keep in mind that that's not the case with trolls of the kind I deal with.

A troll's only goal is to troll. It stays shitty, but if you keep in mind that it's not because of you, or your fault, it's easier to deal with it. :trollface: 

Something I try to keep in mind too: *He needs to create multiple accounts a day and does that all anonymously. He always works over different IPs, for example. I'm pretty sure he spends more time on this then I do deleting the trolling.*


When that guy/girl opened ~100 issues in my repos I did actually throw the tower. But for a few hours, then I got back into it. At the end we're all kinda addicted to this open source thing.

I'm pretty sure if this would have happened when I was totally new to open source I would already have given up. Now I have a reason to stay motivated: the awesome projects I work on and the awesome people I work with.

If you get trolled I think the **I don't care**-strategy is the best one. Actually, I do care, but because I have to take care of deleting it all. The important thing is that you don't care about he says. He's just a troll.

> keep doing so much amazing stuff

Thanks :heart:!

**Comment by passy** [comment]
@arthurvr Fantastic answer! That's a really great way to look at things, I like the numbers approach. As long as you on the receiving end have to invest less time than that person on the other side, you're winning.

**Comment by stevemao** [comment]
> When I made a nitpicky comment and somebody's mad, I feel bad about that, because it's my fault.

No need to feel bad lol. However, I would focus on the problem and the logics first. Once the PR is ready to merge, its definitely important to fix the coding styles etc.

> I'm pretty sure if this would have happened when I was totally new to open source I would already have given up.

No body would do that to repos that are not popular? At least my github experience is quite good :)
