### ISSUE TITLE
What your favourite series/movies?

### ISSUE THREAD

**Issue by drKraken** [arthurvr/ama#2]
:point_up_2:

**Comment by arthurvr** [comment]
Thanks for the question!

I'm a [whovian](https://en.wikipedia.org/wiki/Doctor_Who).

Not only because the serie is fantasic, mainly because of its awesome community. I have a HUGE bunch of doctor who toys and goodies and attend a bunch of doctor who conferences. 

_My favorite doctor is David Tennant._

-

Besides from Doctor who, my style of movies/series is pretty undefined. I like most of the things I see. Lately, I liked [Orange Is the New Black](https://en.wikipedia.org/wiki/Orange_Is_the_New_Black), [Silicon Valley](http://www.imdb.com/title/tt2575988/), [Jurrasic World](http://www.imdb.com/title/tt0369610/) and many other things.
