### ISSUE TITLE
What conferences will you attend this year?

### ISSUE THREAD

**Issue by robbbz** [arthurvr/ama#52]
Related: #50, but I'm wondering if there's anything else.

**Comment by arthurvr** [comment]
I'm not that into conferences. The rare times I attend conferences are because I don't want to miss OSS team meetings. I also decline all invitations I get to talk at conferences or meetups. I don't have a really good explanation why, it's just not really my thing. 

I prefer to just meet with somebody, have fun, chat and hack without all overhead of being at a conference.
